<a href="https://colab.research.google.com/github/sylviayanz/2023-Predictive-Analytics/blob/main/diamond_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import seaborn as sns


from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score
from math import sqrt
from sklearn.model_selection import train_test_split
from sklearn import metrics

sns.set()

In [20]:
model = '/content/drive/MyDrive/LaGuardia Class/assignment/decision_tree.pkl'

In [21]:
import pickle

# Load the saved Decision Tree model
with open(model, 'rb') as file:
    model = pickle.load(file)


In [22]:
test_x = np.zeros((1,26))
test_x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
#data.loc[10]-->price = 339.0

test_x = np.zeros((1, 26))

test_x[0, 0] = 0.30     # carat
test_x[0, 1] = 64.00    # depth
test_x[0, 2] = 55.00    # table
test_x[0, 3] = 4.25     # x
test_x[0, 4] = 4.28     # y
test_x[0, 5] = 2.73     # z
test_x[0, 6] = 0.00     # cut_Fair
test_x[0, 7] = 1.00     # cut_Good
test_x[0, 8] = 0.00     # cut_Ideal
test_x[0, 9] = 0.00     # cut_Premium
test_x[0, 10] = 0.00    # cut_Very Good
test_x[0, 11] = 0.00    # color_D
test_x[0, 12] = 0.00    # color_E
test_x[0, 13] = 0.00    # color_F
test_x[0, 14] = 0.00    # color_G
test_x[0, 15] = 0.00    # color_H
test_x[0, 16] = 0.00    # color_I
test_x[0, 17] = 1.00    # color_J
test_x[0, 18] = 0.00    # clarity_I1
test_x[0, 19] = 0.00    # clarity_IF
test_x[0, 20] = 1.00    # clarity_SI1
test_x[0, 21] = 0.00    # clarity_SI2
test_x[0, 22] = 0.00    # clarity_VS1
test_x[0, 23] = 0.00    # clarity_VS2
test_x[0, 24] = 0.00    # clarity_VVS1
test_x[0, 25] = 0.00    # clarity_VVS2
test_x


array([[ 0.3 , 64.  , 55.  ,  4.25,  4.28,  2.73,  0.  ,  1.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,
         0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ]])

In [24]:
# Make predictions using the loaded Decision Tree model
prediction = model.predict(test_x)
print(f'The Decision Tree model predicts the diamond price as ${round(float(prediction[0]), 2)}')


The Decision Tree model predicts the diamond price as $339.0


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


Got the exactly corret answer

In [25]:
#data.loc[20]-->price = 351.0

test_x = np.zeros((1, 26))

test_x[0, 0] = 0.30     # carat
test_x[0, 1] = 63.30    # depth
test_x[0, 2] = 56.00    # table
test_x[0, 3] = 4.26     # x
test_x[0, 4] = 4.30     # y
test_x[0, 5] = 2.71     # z
test_x[0, 6] = 0.00     # cut_Fair
test_x[0, 7] = 1.00     # cut_Good
test_x[0, 8] = 0.00     # cut_Ideal
test_x[0, 9] = 0.00     # cut_Premium
test_x[0, 10] = 0.00    # cut_Very Good
test_x[0, 11] = 0.00    # color_D
test_x[0, 12] = 0.00    # color_E
test_x[0, 13] = 0.00    # color_F
test_x[0, 14] = 0.00    # color_G
test_x[0, 15] = 0.00    # color_H
test_x[0, 16] = 1.00    # color_I
test_x[0, 17] = 0.00    # color_J
test_x[0, 18] = 0.00    # clarity_I1
test_x[0, 19] = 0.00    # clarity_IF
test_x[0, 20] = 0.00    # clarity_SI1
test_x[0, 21] = 1.00    # clarity_SI2
test_x[0, 22] = 0.00    # clarity_VS1
test_x[0, 23] = 0.00    # clarity_VS2
test_x[0, 24] = 0.00    # clarity_VVS1
test_x[0, 25] = 0.00    # clarity_VVS2
test_x

array([[ 0.3 , 63.3 , 56.  ,  4.26,  4.3 ,  2.71,  0.  ,  1.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ]])

In [26]:
# Make predictions using the loaded Decision Tree model
prediction = model.predict(test_x)
print(f'The Decision Tree model predicts the diamond price as ${round(float(prediction[0]), 2)}')


The Decision Tree model predicts the diamond price as $351.0


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


That's also the correct answer for diamond price of data.loc[20]

In [27]:
#data.loc[371] --> price = 2808.0

test_x = np.zeros((1, 26))

test_x[0, 0] = 0.58     # carat
test_x[0, 1] = 60.90    # depth
test_x[0, 2] = 56.00    # table
test_x[0, 3] = 5.41     # x
test_x[0, 4] = 5.43     # y
test_x[0, 5] = 3.30     # z
test_x[0, 6] = 0.00     # cut_Fair
test_x[0, 7] = 0.00     # cut_Good
test_x[0, 8] = 1.00     # cut_Ideal
test_x[0, 9] = 0.00     # cut_Premium
test_x[0, 10] = 0.00    # cut_Very Good
test_x[0, 11] = 0.00    # color_D
test_x[0, 12] = 1.00    # color_E
test_x[0, 13] = 0.00    # color_F
test_x[0, 14] = 0.00    # color_G
test_x[0, 15] = 0.00    # color_H
test_x[0, 16] = 0.00    # color_I
test_x[0, 17] = 0.00    # color_J
test_x[0, 18] = 0.00    # clarity_I1
test_x[0, 19] = 0.00    # clarity_IF
test_x[0, 20] = 0.00    # clarity_SI1
test_x[0, 21] = 0.00    # clarity_SI2
test_x[0, 22] = 0.00    # clarity_VS1
test_x[0, 23] = 0.00    # clarity_VS2
test_x[0, 24] = 0.00    # clarity_VVS1
test_x[0, 25] = 1.00    # clarity_VVS2
test_x

array([[ 0.58, 60.9 , 56.  ,  5.41,  5.43,  3.3 ,  0.  ,  0.  ,  1.  ,
         0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ]])

In [28]:
# Make predictions using the loaded Decision Tree model
prediction = model.predict(test_x)
print(f'The Decision Tree model predicts the diamond price as ${round(float(prediction[0]), 2)}')


The Decision Tree model predicts the diamond price as $2808.0


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
